Add tax support for DKB on dividends
codeofsumit/tresor-import pull request #103
Opened 2020-09-05 17:02 UTC by jhonnen

This changes adds tax support for dividends only (I don't have other documents with taxes available). -> #24 

Currently the import treats the payout (i.e. net amount after taxes) as the reported amount (and calculates the per share price from that).
That seems wrong to me, the amount should be gross, not net - same as for sells.

2020-09-05 20:17 UTC, dredav requested changes

2020-09-05 20:17 UTC, dredav commented on src/brokers/dkb.js
> +  return +Big(kap).plus(Big(soli));
Can you add also the church tax with the label `Kirchensteuer`?

2020-09-05 20:17 UTC, dredav commented on src/brokers/dkb.js
> +    tax = 0; // TODO
I think you can also use here the `findTax` function. At some other brokers the tax structure is the same for sell and dividend documents.

2020-09-05 20:17 UTC, dredav commented on src/brokers/dkb.js
> +    tax = 0.0;
Can be `0`

2020-09-06 16:20 UTC, jhonnen commented on src/brokers/dkb.js
> +  return +Big(kap).plus(Big(soli));
Done, also added Quellensteuer

2020-09-08 14:17 UTC, codeofsumit commented
Great fix! Can you resolve the merge conflicts? Would be happy to merge this 👌

2020-09-08 18:42 UTC, dredav approved these changes

2020-09-08 19:10 UTC, merged

2020-09-08 19:10 UTC, codeofsumit commented
👏 👏

2020-09-10 16:57 UTC, jhonnen commented
Is this change live already?

2020-09-18 07:48 UTC, SirGibihm commented
I just checked it against the version currently on tresor.one, it does not seem to be online as of yet.

2020-09-18 20:31 UTC, dredav commented
@jhonnen @SirGibihm This change is merged, but currenly not live on production. I think this will come in the next days when Sumit is ready.

2020-09-19 12:03 UTC, codeofsumit commented
It's live now