[ebase] parser and testcases added, little test refactoring
codeofsumit/tresor-import pull request #106
Opened 2020-09-10 12:44 UTC by SirGibihm

This pull request implements a parser for ebase documents. As stated in the according issue #105 There might exist transaction types (i actually am quite sure there are) which could not be covered yet, as I do not have the necessary data to implement them. This pull request also applies some light refactoring as required in issue #104 . 
  
**I am not a seasoned .js developer so I might have overlooked sth.** However, all tests are running smoothly. If additional changes need to be made, feel free to tell me what to change.

2020-09-13 07:54 UTC, carstenhag commented
Please make sure to use Big.js to read in the numbers for the best possible precision. Currently you are using parseFloat which can lead to problems AFAIK. See the other brokers for Big.js usage. Thanks for creating the PR :).

2020-09-13 21:06 UTC, SirGibihm commented
Thanks for the hint with Big.js, it actually fixed a bug I did not know I had. Futhermore, I removed code redundancy and also use helper functions that are given instead of writing them myself.

2020-09-14 18:23 UTC, dredav requested changes
Could you also resolve the merge conflicts?

2020-09-14 18:23 UTC, dredav commented on tests/brokers/consorsbank.test.js
> -import {
I'm sure, that the old formating is the right one - autoformatted by the precommit hock. Did you run the precommit hock?

2020-09-14 18:23 UTC, dredav commented on src/brokers/ebase.js
> +  const valid = every(values(activity), a => !!a || a === 0);
Could you use the new validate function from here: https://github.com/codeofsumit/tresor-import/blob/088cba4e7123bc83ad2cc5cebfb9243ebb4943a7/src/helper/index.js#L37

2020-09-14 18:23 UTC, dredav commented on src/brokers/ebase.js
> +) => textArr.some(t => t.includes('Fondsertrag / Vorabpauschale'));
Does all documents contains `Fondsertrag / Vorabpauschale`? Shoud the checks here not the action name from `paseData` like `Ansparplan`?

2020-09-14 18:23 UTC, dredav commented on src/brokers/ebase.js
> +export const canParseData = (
Why use an extra method and not put the logic in `parsePages`?

2020-09-16 09:19 UTC, SirGibihm commented on tests/brokers/consorsbank.test.js
> -import {
I reformatted it slightly as you recommended. However I left my version of the firstline for clearing up the import:  
```import { getBroker } from '@/index';```
instad of 
```import { getBroker } from '../../src';```
and also removed the double underscores from ```__mock__```. If you want me to undo those as well, please tell me and I will adjust the code.

2020-09-16 10:54 UTC, dredav commented on tests/brokers/consorsbank.test.js
> -import {
That looks good for me after dfcd343887de404097038cba33f18fe3650aa82b! Thanks.

2020-09-16 14:27 UTC, SirGibihm commented on src/brokers/ebase.js
> +  const valid = every(values(activity), a => !!a || a === 0);
Did so, Tests are working fine

2020-09-16 14:29 UTC, SirGibihm commented on src/brokers/ebase.js
> +) => textArr.some(t => t.includes('Fondsertrag / Vorabpauschale'));
Not the way I intended it. The ```Fondsertrag / Vorabpauschale```is a string that only occurs in the header row of the PDF page. This will not occur again for individual transactions as the actions have slightly different names in my observations: e. g.  ```Fondsertrag (Ausschüttung)```.

2020-09-16 14:33 UTC, SirGibihm commented on src/brokers/ebase.js
> +export const canParseData = (
You are right, reduced unnecessary clutter.

2020-09-16 14:39 UTC, SirGibihm commented
I think I got it ready for merge through a rebase on my side, fingers crossed.

2020-10-02 18:25 UTC, SirGibihm commented
I adjusted the Pull Request to be merge-conflict free with the newest changes made in traderepublic. The refactoring regarding issue #104 did not mix well with my changes. Should be mergable by now. Please review.

2020-10-09 18:21 UTC, SirGibihm commented
So yeah, this pull request is utter bull****. The need for a rebase and to many changes in a single pull request made this a mess. I redid my work properly and will set up a new, less messy pull request that incorporates the work I have done.

2020-10-09 18:21 UTC, closed without merging