[Erste Bank] Implemented a new parser
codeofsumit/tresor-import pull request #190
Opened 2020-10-28 22:12 UTC by SirGibihm

Parser for ersteBank implemented, **only Buy operations** are supported as I do not have more samples to check against. Fix #188 

Open question: Should the attribut ```company``` include the suffix detailing in on what it is? e. G. for [this](https://github.com/SirGibihm/tresor-import/blob/4b6112e6d14bac21e6bfa278e5d81391538b8a67/tests/brokers/__mocks__/ersteBank/buy/limit_buy_stock_AT0000APOST4.json#L48-L49) buy order I would assume to be 
* ```const company = OESTERREICHISCHE POST AG``` instead of 
* ```const company = OESTERREICHISCHE POST AG AKTIEN O.N.```

Could someone confirm please?

2020-10-28 22:49 UTC, codeofsumit commented
@SirGibihm I would like to give you all the context around this field so you can make this decision yourself.

This field is used to automatically search a security for this activity if no ISIN or WKN is present. This happens very rarely. Both options would work fine in many cases.

If the result of the search for that name is !== 1 (so we have no, or more than 1 result), user input is required to search/choose a security as a holding for the activity.

I hope this gave you a better context - please let me know if something is unclear.

2020-10-29 11:20 UTC, SirGibihm commented
@codeofsumit Perfect, thank you. That solved my question, no changes to the pull are necessary 👍

2020-10-29 18:58 UTC, codeofsumit commented
Will this PR replace and close #54 ?

2020-10-29 19:00 UTC, SirGibihm commented
@codeofsumit Yes it will, just checked through it

2020-10-30 18:21 UTC, SirGibihm commented
The testfiles you mentioned are an array of dimension 1, see [here](https://github.com/thomaseitler/tresor-import/tree/erstebank/tests/brokers/__mocks__/erstebank). ALL other testdata (.json) is an array of dimension two. I assume there has been a change with how .pdf files are jsonified, could you confirm? If so, I wouldn't really trust these older .json files. I asked the the author of #54 wether he could verify this

2020-10-30 18:32 UTC, dredav commented
@SirGibihm You can add basically the second dimension manually. At an earlier stage, only for some broker (like onvista) the files was parsed to handle possible other pages. I've done already some migrations (a538bdd6b5c3a9879283e1541a4541659d7048cc, 6d40a960ecfcd8b41753c777e905b322820a88b1, ...).

2020-10-30 23:26 UTC, SirGibihm commented
Should initial charges (Ausgabeaufschläge) also be part of the fee if they are listed? Most etfs include them in the Kurswert without stating them explicitely however in this case some of the testfiles list them.

2020-10-31 06:42 UTC, dredav commented
I would say yes, when these are explicitly listed.

2020-11-02 20:04 UTC, SirGibihm commented
This PR is now ready to merge from my side. I would ask the reviewer to check `tests/brokers/__mocks__/ersteBank/buy/2017_buy_1.json` For me, the numbers don't really make sense as the value of the stock (Kurswert) and the amount being taken from your account (Zwischensumme) diverge quite heavily. I assume this has to do with the file being a testfile but I am not sure of this.

2020-11-03 22:18 UTC, dredav requested changes

2020-11-03 22:18 UTC, dredav commented on src/brokers/ersteBank.js
> +const findTaxPayout = pageArray => {
What did you think, did we need to handle also the `KESt I` case without having a sample for it?

>KEST I
Sie ist von Dividendenerträgen inländischer Kapitalgesellschaften in der Höhe von 25% einzubehalten und an das Finanzamt abzuführen. Seit 1. April 2004 unterliegen ausländische Dividenden, die von einer inländischen Bank ausbezahlt werden, der KEST I Neu in der Höhe von 10% (auf die KEST von 25% wird die ausländische QEST in der maximalen Höhe von 15% angerechnet).

Source: https://www.gessler.at/aktuelles/steuer-aktuell.html?related=KESt-1-2-3&art_id=531

2020-11-03 22:18 UTC, dredav commented on src/brokers/ersteBank.js
> +    isin = findIsinPayout(pdfPagesConcat, 'Ausschüttung', 0, 2);
`findIsinPayout` has only one parameter but is invoked with four?

2020-11-03 22:18 UTC, dredav commented on src/brokers/ersteBank.js
> +};
I think this is not the right date. See sample `limit_buy_stock_US02209S1033.json`: The order was created at 11.11.19, but executed at 12.11.19. The total amount was billed at `14.11.19`. You take the last date. I think we need to take the second one.

2020-11-03 22:18 UTC, dredav commented on tests/brokers/ersteBank.test.js
> +    test('Map the buy order for dividend from 2018 correctly', () => {
`2019`

2020-11-04 15:25 UTC, SirGibihm commented on src/brokers/ersteBank.js
> +    pageArray.findIndex(line => line.includes('ckzahl')) + 1;
I do not know how the PDF->.json parser works tbh but generally speaking, PDF is one hell of a flawed document format. Don't even get me started on the security of their signatures :D

2020-11-04 15:26 UTC, SirGibihm commented on src/brokers/ersteBank.js
> +  if (foreignIndex > 0) {
Fixed it.

2020-11-04 15:26 UTC, SirGibihm commented on src/brokers/ersteBank.js
> +    line.includes('umgerechneter FW - Endwert')
Yep, fixed it.

2020-11-04 15:40 UTC, SirGibihm commented on src/brokers/ersteBank.js
> +    }
Technically yes. However, I tend to disagree with changing this line as it seems harder to read imo.

2020-11-04 15:43 UTC, SirGibihm commented on src/brokers/ersteBank.js
> +const findTaxPayout = pageArray => {
Since the logic between `KEst III` and `KEst II` is consistent, I think we should try it. Implementing it with a comment warning about it not being tested.

2020-11-04 15:44 UTC, SirGibihm commented on src/brokers/ersteBank.js
> +    isin = findIsinPayout(pdfPagesConcat, 'Ausschüttung', 0, 2);
Thats a refactoring remainder from a previous uncommitted version, removed it.

2020-11-04 15:46 UTC, SirGibihm commented on src/brokers/ersteBank.js
> +};
I recall we had a discussion to take the valuta for dividends and focused on that. But now that you notice me about it, I think you are right. Fixed it.

2020-11-04 15:56 UTC, SirGibihm commented on tests/brokers/ersteBank.test.js
> +    test('Map the buy order for dividend from 2018 correctly', () => {
Fixed

2020-11-04 18:58 UTC, dredav commented on src/brokers/ersteBank.js
> +    pageArray.findIndex(line => line.includes('ckzahl')) + 1;
I'm working for an output management company and processing pdf is my daily business 🙈  The most documents are fine, but it feels that some document generators will only generate 💩.

2020-11-04 19:04 UTC, dredav approved these changes
Nice one! We got an new supported broker 🎉

2020-11-04 19:06 UTC, dredav commented
And @codeofsumit can enter a new market in austria. With the currency support feature the next market can be switzerland so complete DACH 😆

2020-11-04 19:13 UTC, codeofsumit commented
🤯  boom, nice

2020-11-04 19:13 UTC, merged

2020-11-09 22:47 UTC, kajdo commented
cool .... will keep my branch for another couple of days and test your implementation :) .... thx for the support - i didn't manage to get back to it :) :+1:

2020-11-19 23:24 UTC, kajdo commented
any updates when the import will be available in T1? what's the actual process (could start to work on the dividents somewhen in december to push it another step foreward)

2020-11-20 16:43 UTC, dredav commented
> any updates when the import will be available in T1?
 
We are planning to make a new release this weekend.