[comdirect] Correctly parses witholding tax for dividends/payouts
codeofsumit/tresor-import pull request #194
Opened 2020-10-29 15:16 UTC by SirGibihm

Now shows the dividend/payout withholding tax for comdirect correctly. See #192 Also implements the attributes fxRate and foreignCurrency for comdirect dividends

2020-10-29 22:20 UTC, dredav requested changes

2020-10-29 22:20 UTC, dredav commented on src/brokers/comdirect.js
> +const findPayoutFxRate = textArr => {
The logic is basically the same as in `findBuyFxRate`? We can search the line with `zum Devisenkurs` and get the same result with only one function right?

2020-10-29 22:20 UTC, dredav commented on src/brokers/comdirect.js
> +  if (!(fxRate === undefined)) {
```suggestion
  if (fxRate !== undefined) {
```

2020-10-29 22:20 UTC, dredav commented on src/brokers/comdirect.js
> +    const withholdingTax = parseGermanNum(
Can we put this block into the condition `withholdingTaxIndex > 0`? Better safe than sorry.

2020-10-29 22:20 UTC, dredav commented on src/brokers/comdirect.js
> +const findPayoutTax = (textArr, fxRate) => {
I've fixed recently an related issue with the withholding tax. The withholding tax can also apply within the european union (e.g. Dividends from Netherlands). In this case we don't have an fxRate but need to find the withholding tax amount.

2020-10-29 22:20 UTC, dredav commented on src/brokers/comdirect.js
> +    // For dividend operations:
This comment is for dividend but we are in a buy function.

2020-10-29 22:20 UTC, dredav commented on src/brokers/comdirect.js
> +  if (!(fxRate === undefined) && !(foreignCurrency === undefined)) {
Thats to much duplicated code for me.. Why not adding the field to the above created activity, only when a value is set like:
```js
  if (fxRate !== undefined) {
    activity.fxRate = fxRate;
  }
```

2020-10-30 18:37 UTC, SirGibihm commented on src/brokers/comdirect.js
> +const findPayoutFxRate = textArr => {
Yeah I had this in a previous version but decided against that for an unknown reason. Combined the logic in a single function that returns an array with two entries. Fixed

2020-10-30 18:38 UTC, SirGibihm commented on src/brokers/comdirect.js
> +  if (!(fxRate === undefined)) {
Fixed, is there a reason to do it like this apart from readability?

2020-10-30 18:39 UTC, SirGibihm commented on src/brokers/comdirect.js
> +    const withholdingTax = parseGermanNum(
Absolutely

2020-10-30 18:43 UTC, dredav commented on src/brokers/comdirect.js
> +  if (!(fxRate === undefined)) {
For me its easier to read because after reading you don't have to negate twice.

2020-10-30 18:45 UTC, SirGibihm commented on src/brokers/comdirect.js
> +const findPayoutTax = (textArr, fxRate) => {
The function now checks wether fxRate is defined and > 0. If so it returns divides the `withholding tax/fxRate`, otherwise it just returns the `withholding tax`

2020-10-30 18:46 UTC, SirGibihm commented on src/brokers/comdirect.js
> +    // For dividend operations:
`Bad David, don't copy paste your own code and comments` ;) Fixed it

2020-10-30 18:56 UTC, SirGibihm commented on src/brokers/comdirect.js
> +  if (!(fxRate === undefined) && !(foreignCurrency === undefined)) {
You can do that?! Google told me it wasn't possible. Gladly adjusting it as it pained me too!

2020-10-30 18:57 UTC, SirGibihm commented
@dredav I implemented your changes. Please re-review and verify that everything is to your liking. Thanks for the feedback!

2020-10-30 20:55 UTC, dredav reviewed
Looks great. I've only one question (see the review comment) - but it's a minor thing.

2020-10-30 20:55 UTC, dredav commented on src/brokers/comdirect.js
> +const findBuyFxRate = textArr => {
Can we also combine `findBuyFxRate` and `findBuyForeignCurrency`? Or is `findBuyFxRate` and `findBuyForeignCurrency` not the same as `findPayoutFxrateForeignCurrency` except the search term `line.includes('zum Devisenkurs:')` and `line.includes('Umrechnung zum Devisenkurs ')` which may can also be only `zum Devisenkurs`?

2020-10-30 22:08 UTC, SirGibihm commented on src/brokers/comdirect.js
> +const findBuyFxRate = textArr => {
I was able to reduce the functions `findBuyFxRate` and `findBuyForeignCurrency` to `findBuyFxRate` but I can't make it all one function for both dividends and buy transactionsas the structure of the line containing ```Umrechnung zum Devisenkurs``` is different between Buy and Dividend transactions:
* Buy: ```Umrechnung zum Devisenkurs 1,176100        : EUR               74,99```
* Dividend: ```zum Devisenkurs: EUR/USD      1,175600                 EUR               0,43```

I'm sure I could mix that together but that wouldn't be readable code in my opinion.

2020-10-31 03:38 UTC, dredav commented on src/brokers/comdirect.js
> +const findBuyFxRate = textArr => {
Sgtm 🙃

2020-10-31 03:39 UTC, dredav approved these changes

2020-10-31 09:32 UTC, merged