[smartbroker] Add `fxRate` and `foreignCurrency`. Fix issue with `Kirchensteuer`.
codeofsumit/tresor-import pull request #298
Opened 2020-11-27 22:35 UTC by dredav

- Fix #292 
- Fix #293 
- Add test cases from #292 & #293 
- Add properties `fxRate` and `foreignCurrency`
- Fix tax logic when `Solidaritätszuschlag` was present but `Kirchensteuer` isn't

2020-11-30 18:21 UTC, SirGibihm approved these changes

2020-11-30 18:21 UTC, SirGibihm commented on src/brokers/smartbroker.js
> +  }
This can be simplified (Not sure if its simpler though) using a `?`. I guess for the sake of readability `if [...] else` is the better solution.
```javascript 
const fxInfo= lineContent.includes(' ') ? regex.exec(lineContent) : regex.exec(content[fxRateLineNumber + 1]);
```
In any case I would prefer the `if` condition not be be negated for readability. No functional complaints though

2020-12-02 15:41 UTC, codeofsumit requested changes
`datetime` is finally merged. But created some last merge conflicts here

2020-12-02 20:14 UTC, dredav commented
Conflicts solved!

2020-12-02 21:20 UTC, SirGibihm approved these changes

2020-12-02 22:20 UTC, merged