[Cortal Consors] Add support for "new" broker
codeofsumit/tresor-import pull request #302
Opened 2020-11-28 22:28 UTC by dredav

- This PR replace the old one #77
- Fix #228, #230, #232, #301
- Add test cases
- Update test structure and test cases
- Use `validateActivity` function, dividend payout use now the gross amount, dividend date now set to pay date
- Parse `Provision` as fee
- Add test case and add support for etf dividends
- Add church tax parsing

2020-11-30 18:36 UTC, SirGibihm requested changes
Sligth changes requested. Sadly, the example documents don't allow for the implementation of FxRates etc. to be implemented as of yet. Furthermore, could you check wether the logic of this broker is the same as for smartbroker and onvista? I can't code too much atm myself so I could not check it.

EDIT: Merge conflicts, gotta love ESLINT 👯

2020-11-30 18:36 UTC, SirGibihm commented on tests/brokers/__mocks__/cortalconsors/sell/2014_allianz.json
> +    "BNP Paribas S.A. Niederlassung Deutschland",
Yet another BNP Paribas Broker. There might be a lot of code duplication

2020-11-30 18:36 UTC, SirGibihm commented on tests/brokers/cortalconsors.test.js
> +          date: '2014-03-07',
Datetime is not supported by can be extracted from the .pdf. Could you add that functionality please?

2020-11-30 18:36 UTC, SirGibihm commented on src/brokers/cortalconsors.js
> +  const date = textArr[idx + 2].substr(3, 10).trim();
You don't use the function that helps you with parsing the time from the helper class, is this on purpose?

2020-11-30 18:36 UTC, SirGibihm commented on src/brokers/cortalconsors.js
> +  return line.split(/\s+/)[1];
Same here with the date function

2020-11-30 19:47 UTC, dredav commented
@SirGibihm hmm yes. I dismissed the datetime logic becase of doing a pull request against the master branch and the datetime logic is not merged yes - but we need to do this. So I can rebase this feature again my datetime PR and we need to merge that feature first and then this one.

2020-12-02 05:47 UTC, dredav commented on tests/brokers/__mocks__/cortalconsors/sell/2014_allianz.json
> +    "BNP Paribas S.A. Niederlassung Deutschland",
I don't compare all functions, but the first functions I compared has quite different content.

2020-12-02 20:49 UTC, SirGibihm approved these changes

2020-12-02 20:51 UTC, merged