[unioninvest] Fixes an issue where .pdf files have a totally different format
codeofsumit/tresor-import pull request #325
Opened 2020-12-02 15:16 UTC by SirGibihm

As the title states, some unioninvest .pdf files have a totally different format than the one we implemented allready.
Fix #134

2020-12-05 17:11 UTC, dredav requested changes
Looks good. Some work is ongoing (we already discussed), see also #364.

2020-12-05 17:11 UTC, dredav commented on src/brokers/unioninvest.js
> +    findPriorRegexMatch(pdfPage, activityIdx, /[0-9]{2}\.[0-9]{2}\.[0-9]{4}/) -
Whats the need for returning the lineNumber instead the line value (or both)?

2020-12-06 20:27 UTC, SirGibihm commented on src/brokers/unioninvest.js
> +    findPriorRegexMatch(pdfPage, activityIdx, /[0-9]{2}\.[0-9]{2}\.[0-9]{4}/) -
Because the line value is quite rareley needed (admittedly, in this case it is). Furthermore, I did not want the function to be overly complex; thus I don't return the value and the index

2020-12-06 20:29 UTC, SirGibihm commented on src/brokers/unioninvest.js
>  export const parsePages = pdfPages => {
Could you elaborate? What do we need the try carch for exaclty?

2020-12-08 05:50 UTC, dredav commented on src/brokers/unioninvest.js
>  export const parsePages = pdfPages => {
I've checked your code again and it looks good. So my comment is solved. My comment was about the documents where the first pages contains only text (not related to an activity) and the activities are on a page backwards.

2020-12-08 06:05 UTC, dredav commented
Nice. 66 of 72 documents are working right now with this PR. For the other six I created #395. I can imagine your hate again this broker 🙈

2020-12-10 23:06 UTC, SirGibihm commented
@dredav So yeah, I added thos files as well. Now please end my suffering and just kill me. But in all seriousness; the files are working now but it required a lot of refactoring. I suppose it will take some time for you to review this but I am moderatly confident, that we got 95% of the edgecases this time around. So the testfiles were bang on!

2020-12-15 05:37 UTC, dredav approved these changes
Hell yes, all the documents can be parsed! 

What for a broker, thanks for your time to get the work done. It's a honor to approve this one, but I will let you merge this big one.

Hopefully we never need to adjust the logic for this broker 🙏

2020-12-15 08:17 UTC, SirGibihm commented on tests/brokers/unioninvest.test.js
> +    test('Can parse a redistribution from 2016', () => {
Fixed

2020-12-15 08:17 UTC, SirGibihm commented on src/brokers/unioninvest.js
> +    findPriorRegexMatch(pdfPage, activityIdx, /[0-9]{2}\.[0-9]{2}\.[0-9]{4}/) -
Fixed

2020-12-15 08:19 UTC, SirGibihm commented
@dredav Fixed the issues, this should do it!

2020-12-16 05:10 UTC, dredav approved these changes

2020-12-16 07:22 UTC, merged