[degiro] Fixes a Buy-Sell identification bug; adding support for swiss degiro broker (minor)
codeofsumit/tresor-import pull request #468
Opened 2020-12-13 18:22 UTC by SirGibihm

Due to a little Bug `Sell`s are identified as `Buy`s. Fixed that
* Fixes #464

Added support for the swiss variant of degiro, which required only miniscule change of the code
* On swiss documents the swiss number format (-13.37) instead of the german (-13,37) number format is used
* no further format changes
* Fixes #465

2020-12-13 21:06 UTC, dredav commented
One question: The activities from degiro.ch are in `CHF`. So the base currency is not `EUR` which is currently not supported by T1, right?

2020-12-13 21:41 UTC, SirGibihm commented
> 
> 
> One question: The activities from degiro.ch are in `CHF`. So the base currency is not `EUR` which is currently not supported by T1, right?

Yeah I did not think about that but thats completely True... The user would see his or her transactions in the wrong currency;  now that I think about it I should revert the change. What do you think @codeofsumit ?

2020-12-13 21:55 UTC, dredav commented
But we can made `canParsePage` more open. So that all degiro countries with `EUR` are supported, what did you think @SirGibihm? (all degiros are listed here: https://www.degiro.eu)

2020-12-13 22:02 UTC, SirGibihm commented
> 
> 
> But we can made `canParsePage` more open. So that all degiro countries with `EUR` are supported, what did you think @SirGibihm? (all degiros are listed here: https://www.degiro.eu)

Awesome idea! Implemented all € countries where degiro operates!

2020-12-14 18:52 UTC, dredav requested changes
Found one little debug thing which should removed before merging.

2020-12-14 18:52 UTC, dredav commented on src/brokers/degiro.js
> +  }
Could you remove the debug part?

2020-12-14 19:41 UTC, SirGibihm commented on src/brokers/degiro.js
> +  }
Thats no debug part; I use Debuggers, I promise! I am a competent programmer!! (Removed the debugging part).

2020-12-14 19:42 UTC, SirGibihm commented
@dredav Ready to go

2020-12-14 20:22 UTC, dredav approved these changes

2020-12-14 20:24 UTC, merged