[trade republic] Add status code to ignore some type of documents
codeofsumit/tresor-import pull request #481
Opened 2020-12-15 05:47 UTC by dredav

- Implement status codes `7` and `8`
- The following trade republic documents will return status code `8`: `KOSTENINFORMATION `, `SPARPLANAUSFÜHRUNG FEHLGESCHLAGEN`, `SPLIT`, `REVERSE SPLIT`
- Fix #451 (and all related issues)
- Add test cases for all the above documents
- Other implementations will soon be adjusted

2020-12-15 08:34 UTC, SirGibihm requested changes

2020-12-15 08:34 UTC, SirGibihm commented on src/brokers/traderepublic.js
I am unsure why we require satus code 7 . Couldn't we return false for `canParsePage()` if `(isSupportedDocument(firstPdfPage) || detectedButIgnoredDocument(firstPdfPage))`?

2020-12-15 08:34 UTC, SirGibihm commented on src/brokers/traderepublic.js
> +    content.some(line => line === 'REVERSE SPLIT')
Easier and more resource efificient I think: `content.includes('SPLIT')`. Also two comments explaining the same thing; am I right?

2020-12-16 05:24 UTC, dredav commented on src/brokers/traderepublic.js
> +    content.some(line => line === 'REVERSE SPLIT')
Yes you are!

2020-12-16 05:24 UTC, dredav commented on src/brokers/traderepublic.js
Good idea. We can remove one of the status code and it's easier to understand.

2020-12-16 05:26 UTC, dredav commented
@SirGibihm Changes are in.

2020-12-16 07:23 UTC, SirGibihm approved these changes

2020-12-16 07:25 UTC, merged