Change ISIN Regex to match all valid country codes
codeofsumit/tresor-import pull request #943
Opened 2021-01-09 07:16 UTC by dredav

- Add sample from #917
- Fix #917: Use now all ISO 3166-1 alpha-2 county codes

2021-01-09 11:00 UTC, SirGibihm requested changes

2021-01-09 11:00 UTC, SirGibihm commented on src/helper/index.js
> +export const isinRegex = /^(AA|AB|AC|AD|AE|AF|AG|AH|AI|AJ|AK|AL|AM|AN|AO|AP|AQ|AR|AS|AT|AU|AV|AW|AX|AY|AZ|BA|BB|BC|BD|BE|BF|BG|BH|BI|BJ|BK|BL|BM|BN|BO|BP|BQ|BR|BS|BT|BU|BV|BW|BX|BY|BZ|CA|CB|CC|CD|CE|
```suggestion
export const isinRegex = /^([A-Z][A-Z])([0-9A-Z]{9})([0-9])$/
```
If we're gonna go for all combinations we might as well regex it

2021-01-09 15:14 UTC, dredav commented
@SirGibihm I've updated the PR.

2021-01-11 08:16 UTC, SirGibihm approved these changes

2021-01-11 08:17 UTC, merged